const WorkoutOptions = [
  "Push Ups",
  "Pull Ups",
  "Squats",
  "Deadlifts",
  "Bench Press",
  "Lunges",
  "Planks",
  "Overhead Press",
  "Barbell Rows",
  "Dumbbell Curls",
  "Tricep Dips",
  "Leg Press",
  "Chest Fly",
  "Cable Crossover",
  "Lat Pulldown",
  "Seated Row",
  "Shoulder Press",
  "Incline Bench Press",
  "Decline Bench Press",
  "Hammer Curls",
  "Preacher Curls",
  "Triceps Pushdown",
  "Leg Curl",
  "Leg Extension",
  "Calf Raises",
  "Russian Twists",
  "Mountain Climbers",
  "Jump Squats",
  "Burpees",
  "Side Plank",
  "Hanging Leg Raises",
  "Ab Wheel Rollout",
  "Kettlebell Swings",
  "Goblet Squat",
  "Zercher Squat",
  "Front Squat",
  "Sumo Deadlift",
  "Romanian Deadlift",
  "Hip Thrust",
  "Cable Kickbacks",
  "Donkey Kicks",
  "Glute Bridges",
  "Step Ups",
  "Box Jumps",
  "Arnold Press",
  "Face Pulls",
  "Reverse Fly",
  "Upright Row",
  "Wrist Curls",
  "Farmer’s Walk",
  "Cable Lateral Raise",
  "Bent Over Lateral Raise",
  "Chest Dips",
  "Push Press",
  "Power Cleans",
  "Snatch",
  "Clean and Jerk",
  "Trap Bar Deadlift",
  "Landmine Press",
  "Landmine Row",
  "Battle Ropes",
  "Medicine Ball Slams",
  "Tire Flips",
  "Sled Push",
  "Sled Pull",
  "Resistance Band Squat",
  "Cable Woodchopper",
  "Cable Crunch",
  "Incline Dumbbell Curl",
  "Concentration Curl",
  "Zottman Curl",
  "Overhead Triceps Extension",
  "Skull Crushers",
  "Close Grip Bench Press",
  "Smith Machine Squat",
  "Hack Squat",
  "Sissy Squat",
  "Standing Calf Raise",
  "Seated Calf Raise",
  "Reverse Crunch",
  "Toe Touches",
  "Bicycle Crunches",
  "Flutter Kicks",
  "Leg Raises",
  "Dragon Flag",
  "Single-Leg Deadlift",
  "Good Mornings",
  "Jefferson Squat",
  "Inverted Row",
  "T-Bar Row",
  "Dumbbell Pullover",
  "Pec Deck Machine",
  "Triceps Kickbacks",
  "Cable Face Pull",
  "Dumbbell Shrugs",
  "Machine Shoulder Press",
  "Machine Chest Press",
  "Chest Supported Row",
  "Incline Cable Fly",
  "One-Arm Dumbbell Row"
];

export default WorkoutOptions;